public class EstqDto
{
    public string? COD_EST { get; set; }
    public string? COD_PRO { get; set; }
    public string? STQ { get; set; }
    public decimal? P_COMER { get; set; }
    public decimal? P_COMPRA { get; set; }
    public decimal? P_CUSTO { get; set; }
    public decimal? P_MEDIO { get; set; }
    public decimal? P_VENDA { get; set; }
    public decimal? P_COMPR_A { get; set; }
    public decimal? P_MEDIO_A { get; set; }
    public decimal? P_VENDA_A { get; set; }
    public decimal? P_CUSTO_A { get; set; }
    public decimal? US_CUSTO { get; set; }
    public decimal? US_VENDA { get; set; }
    public decimal? PCFIXO { get; set; }
    public decimal? QTE { get; set; }
    public decimal? QTE_MIN { get; set; }
    public decimal? QTE_ANT { get; set; }
    public decimal? QTE_MAX { get; set; }
    public string? ORDEMQTE { get; set; }
    public string? NUM_NF { get; set; }
    public DateOnly? DT_COMPRA { get; set; }
    public string? UCCOD_FOR { get; set; }
    public DateOnly? DT_VENDA { get; set; }
    public decimal? QTE_FUT { get; set; }
    public decimal? COMISSAO { get; set; }
    public decimal? COMIS_EXT { get; set; }
    public decimal? P_PROMOCAO { get; set; }
    public string? TV_PROMO { get; set; }
    public decimal? PROMOCAO { get; set; }
    public DateOnly? DT_I_PROM { get; set; }
    public DateOnly? DT_F_PROM { get; set; }
    public string? CURVA { get; set; }
    public string? ENDERECO { get; set; }
    public decimal? Q2 { get; set; }
    public string? D_ALT_PR { get; set; }
    public string? D_AUDIT { get; set; }
    public string? T_AUDIT { get; set; }
    public decimal? Q_AUDIT { get; set; }
    public decimal? PMC { get; set; }
    public decimal? PMCMARKUP { get; set; }
    public string? VALIDADE { get; set; }
    public decimal? P_VISTA { get; set; }
    public decimal? P_VENCALC { get; set; }
    public DateOnly? DTULTLANC { get; set; }
    public decimal? QTE_PADRAO { get; set; }
    public string? CALC_PADR { get; set; }
    public DateOnly? DT_QTEPADR { get; set; }
    public decimal? P_FPOP { get; set; }
    public decimal? VBCSTRET { get; set; }
    public decimal? PST { get; set; }
    public decimal? VICMSSTRET { get; set; }
    public decimal? VICMSSUBST { get; set; }
    public string? NFCI { get; set; }
    public string? CBENEF { get; set; }
    public DateOnly? DATA_INCL { get; set; }
    public DateOnly? DATA_ALT { get; set; }
    public int? N_ALTQ { get; set; }
    public int? N_ALTP { get; set; }
}